### ISSUE TITLE
Ethereum wallet not starting up

### ISSUE THREAD

**Issue by brian2121** [ethereum/meteor-dapp-wallet#106] opened 2016-02-19 14:08 UTC
I am no programmer but have basic computer skills. I have just started using Ether. I have 25 Ether in my Mist wallet but now I cannot access my wallet. I am currently getting the alert message,

' _Couldn't start an Ethereum node! Are you already running a node? Make sure your IPC path is set to the default: $ geth --ipcpath \\.\pipe\geth.ipc_ '

I am at my wits end as to what to do any help would be most appreciated.

**Comment by frozeman** [comment] 2016-02-22 11:56
Please make sure that you don't have already geth running. Try restarting your computer

**Comment by alexvandesande** [comment] 2016-02-23 12:25
Duplicate of https://github.com/ethereum/mist/issues/197

**Closed by alexvandesande** 2016-02-23 12:25 UTC
