### ISSUE TITLE
Ethereum-Wallet-macosx64-0-4-0 stuck on loading nodes splash screen

### ISSUE THREAD

**Issue by arthurleonov** [ethereum/meteor-dapp-wallet#109] opened 2016-02-26 17:24 UTC
Hi guys.

Congrats on all of the progress. However, theres still bugs.  I tried loading the Wallet 0.4.0 (Beta 7) on my mac el capitan v10.11

Its stuck on the "Starting Ethereum node..." screen.

Am I being thick and missing something extra that I need to install? This wallet should work out of the box right.

**Comment by int-peter** [comment] 2016-03-01 09:21
Same here

**Comment by peter-dsgn** [comment] 2016-03-01 09:26
Same here

**Comment by frozeman** [comment] 2016-03-01 10:18
Please look at the existing issues... this is the 1000000's duplicate of https://github.com/ethereum/mist/issues/163

**Closed by frozeman** 2016-03-01 10:18 UTC
