### ISSUE TITLE
Blockchain data directory path hardwired to C:\Users\user\AppData\Roaming\Ethereum

### ISSUE THREAD

**Issue by ConsentDevelopment** [ethereum/meteor-dapp-wallet#238] opened 2016-07-06 17:43 UTC
The blockchain data was taking a lot of room on my C: drive so I changed the location of the path C:\Users\alex-\AppData\Roaming (which contains the Ethereum data folder for the blockchain data) to D:\Roaming.

When I start the wallet there is a error message that it cannot find the node and so it begins to download the whole blockchain again to the path C:\Users\user\AppData\Roaming\Ethereum

As the blockchain will get bigger and bigger a lot of people will want to move the data folder to a bigger drive as the C drive is to small and has all the OS programs and data.

Solution - correctly check and use the Roaming path retrieved from the Windows OS.

OS - Windows 10 64 bit
C: drive 128 GB SSD
D: drive 998 GB

**Comment by luclu** [comment] 2016-07-19 12:46
Duplicate of https://github.com/ethereum/mist/issues/927

**Closed by luclu** 2016-07-19 12:46 UTC
