### ISSUE TITLE
wallet contract notifying erroneous transactions

### ISSUE THREAD

**Issue by newmzy** [ethereum/meteor-dapp-wallet#160] opened 2016-04-30 20:11 UTC
I posted this issue in the general mist issues before finding this.

I created a wallet contract to enable me to see the incoming transaction deatials, but now the wallet is popping up messages about transactions (often for 100 ether) which are not anything to do with me, but are labelled as coming into or going out of my wallet contract. In the attached picture, none of the listed transactions are my transactions, and they (thankfully) had no effect on my balance.
![wallet_transactions](https://cloud.githubusercontent.com/assets/17661766/14938342/cc978dec-0f52-11e6-8a9c-e4aae62f645c.jpg)

**Comment by luclu** [comment] 2016-05-20 08:39
closed as duplicate of https://github.com/ethereum/mist/issues/568

**Closed** 2016-05-25 13:57 UTC
