### ISSUE TITLE
I can't even install mist or ether wallet : Couldn't connect to node? See the logs for more:

### ISSUE THREAD

**Issue by rafa18rg** [ethereum/meteor-dapp-wallet#247] opened 2016-07-21 06:27 UTC
Node type: geth
Network: main
Platform: darwin (Architecure x64)
```
.../database.go:169] closed db:/Users/rafaelreyes/Library/Ethereum/chaindata
I0721 00:27:20.652243 cmd/utils/flags.go:592] WARNING: No etherbase set and no accounts found as default
I0721 00:27:20.689363 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/rafaelreyes/Library/Ethereum/chaindata
I0721 00:27:20.757294 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /Users/rafaelreyes/Library/Ethereum/dapp
I0721 00:27:20.777124 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0721 00:27:20.777235 eth/backend.go:201] Blockchain DB Version: 3
I0721 00:27:20.778152 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
I0721 00:27:20.778165 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
I0721 00:27:20.778170 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184
I0721 00:27:20.779535 p2p/server.go:313] Starting Server
Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use
```
What should I do?

**Comment by luclu** [comment] 2016-07-21 06:51
Duplicate of https://github.com/ethereum/mist/issues?utf8=%E2%9C%93&q=is%3Aissue%20%3A30303%3A%20bind%3A%20address%20already%20in%20use.

**Closed by luclu** 2016-07-21 06:51 UTC
Labels: duplicate
